// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserLoginQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLoginQuery) Reset() {
	*x = UserLoginQuery{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginQuery) ProtoMessage() {}

func (x *UserLoginQuery) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginQuery.ProtoReflect.Descriptor instead.
func (*UserLoginQuery) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserLoginQuery) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type UserLoginQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	User          *UserInfo              `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLoginQueryResponse) Reset() {
	*x = UserLoginQueryResponse{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginQueryResponse) ProtoMessage() {}

func (x *UserLoginQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginQueryResponse.ProtoReflect.Descriptor instead.
func (*UserLoginQueryResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserLoginQueryResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UserLoginQueryResponse) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

type WxLoginPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionKey    string                 `protobuf:"bytes,1,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	Unionid       string                 `protobuf:"bytes,2,opt,name=unionid,proto3" json:"unionid,omitempty"`
	Openid        string                 `protobuf:"bytes,3,opt,name=openid,proto3" json:"openid,omitempty"`
	Errcode       int32                  `protobuf:"varint,4,opt,name=errcode,proto3" json:"errcode,omitempty"`
	Errmsg        string                 `protobuf:"bytes,5,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WxLoginPayload) Reset() {
	*x = WxLoginPayload{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WxLoginPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WxLoginPayload) ProtoMessage() {}

func (x *WxLoginPayload) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WxLoginPayload.ProtoReflect.Descriptor instead.
func (*WxLoginPayload) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *WxLoginPayload) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

func (x *WxLoginPayload) GetUnionid() string {
	if x != nil {
		return x.Unionid
	}
	return ""
}

func (x *WxLoginPayload) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

func (x *WxLoginPayload) GetErrcode() int32 {
	if x != nil {
		return x.Errcode
	}
	return 0
}

func (x *WxLoginPayload) GetErrmsg() string {
	if x != nil {
		return x.Errmsg
	}
	return ""
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Payload       string                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Key           string                 `protobuf:"bytes,5,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserInfo) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *UserInfo) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// 修改用户信息
type UserInfoModifyQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Avatar        string                 `protobuf:"bytes,1,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoModifyQuery) Reset() {
	*x = UserInfoModifyQuery{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoModifyQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoModifyQuery) ProtoMessage() {}

func (x *UserInfoModifyQuery) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoModifyQuery.ProtoReflect.Descriptor instead.
func (*UserInfoModifyQuery) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *UserInfoModifyQuery) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserInfoModifyQuery) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type UserInfoModifyQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoModifyQueryResponse) Reset() {
	*x = UserInfoModifyQueryResponse{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoModifyQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoModifyQueryResponse) ProtoMessage() {}

func (x *UserInfoModifyQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoModifyQueryResponse.ProtoReflect.Descriptor instead.
func (*UserInfoModifyQueryResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

// 主密钥信息设置
type MasterKeySetQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       string                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Ciphertext    string                 `protobuf:"bytes,2,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MasterKeySetQuery) Reset() {
	*x = MasterKeySetQuery{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MasterKeySetQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterKeySetQuery) ProtoMessage() {}

func (x *MasterKeySetQuery) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterKeySetQuery.ProtoReflect.Descriptor instead.
func (*MasterKeySetQuery) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *MasterKeySetQuery) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *MasterKeySetQuery) GetCiphertext() string {
	if x != nil {
		return x.Ciphertext
	}
	return ""
}

type MasterKeySetQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MasterKeySetQueryResponse) Reset() {
	*x = MasterKeySetQueryResponse{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MasterKeySetQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterKeySetQueryResponse) ProtoMessage() {}

func (x *MasterKeySetQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterKeySetQueryResponse.ProtoReflect.Descriptor instead.
func (*MasterKeySetQueryResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *MasterKeySetQueryResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// 主密钥校验
type MasterKeyVerifyQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ciphertext    string                 `protobuf:"bytes,1,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MasterKeyVerifyQuery) Reset() {
	*x = MasterKeyVerifyQuery{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MasterKeyVerifyQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterKeyVerifyQuery) ProtoMessage() {}

func (x *MasterKeyVerifyQuery) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterKeyVerifyQuery.ProtoReflect.Descriptor instead.
func (*MasterKeyVerifyQuery) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *MasterKeyVerifyQuery) GetCiphertext() string {
	if x != nil {
		return x.Ciphertext
	}
	return ""
}

type MasterKeyVerifyQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MasterKeyVerifyQueryResponse) Reset() {
	*x = MasterKeyVerifyQueryResponse{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MasterKeyVerifyQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterKeyVerifyQueryResponse) ProtoMessage() {}

func (x *MasterKeyVerifyQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterKeyVerifyQueryResponse.ProtoReflect.Descriptor instead.
func (*MasterKeyVerifyQueryResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *MasterKeyVerifyQueryResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MasterKeyVerifyQueryResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// 添加应用
type AppAddQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Payload       *AppPayload            `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppAddQuery) Reset() {
	*x = AppAddQuery{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppAddQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppAddQuery) ProtoMessage() {}

func (x *AppAddQuery) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppAddQuery.ProtoReflect.Descriptor instead.
func (*AppAddQuery) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

func (x *AppAddQuery) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppAddQuery) GetPayload() *AppPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type AppAddQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppAddQueryResponse) Reset() {
	*x = AppAddQueryResponse{}
	mi := &file_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppAddQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppAddQueryResponse) ProtoMessage() {}

func (x *AppAddQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppAddQueryResponse.ProtoReflect.Descriptor instead.
func (*AppAddQueryResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{11}
}

type AppPayload struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccountPayload string                 `protobuf:"bytes,1,opt,name=accountPayload,proto3" json:"accountPayload,omitempty"`
	PwdPayload     string                 `protobuf:"bytes,2,opt,name=pwdPayload,proto3" json:"pwdPayload,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AppPayload) Reset() {
	*x = AppPayload{}
	mi := &file_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppPayload) ProtoMessage() {}

func (x *AppPayload) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppPayload.ProtoReflect.Descriptor instead.
func (*AppPayload) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{12}
}

func (x *AppPayload) GetAccountPayload() string {
	if x != nil {
		return x.AccountPayload
	}
	return ""
}

func (x *AppPayload) GetPwdPayload() string {
	if x != nil {
		return x.PwdPayload
	}
	return ""
}

// 应用列表
type AppListQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppListQuery) Reset() {
	*x = AppListQuery{}
	mi := &file_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppListQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppListQuery) ProtoMessage() {}

func (x *AppListQuery) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppListQuery.ProtoReflect.Descriptor instead.
func (*AppListQuery) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{13}
}

func (x *AppListQuery) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AppListQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lists         []*AppInfo             `protobuf:"bytes,1,rep,name=lists,proto3" json:"lists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppListQueryResponse) Reset() {
	*x = AppListQueryResponse{}
	mi := &file_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppListQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppListQueryResponse) ProtoMessage() {}

func (x *AppListQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppListQueryResponse.ProtoReflect.Descriptor instead.
func (*AppListQueryResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{14}
}

func (x *AppListQueryResponse) GetLists() []*AppInfo {
	if x != nil {
		return x.Lists
	}
	return nil
}

type AppInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Payload       *AppPayload            `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppInfo) Reset() {
	*x = AppInfo{}
	mi := &file_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppInfo) ProtoMessage() {}

func (x *AppInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppInfo.ProtoReflect.Descriptor instead.
func (*AppInfo) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{15}
}

func (x *AppInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AppInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppInfo) GetPayload() *AppPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x04user\"$\n" +
	"\x0eUserLoginQuery\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"R\n" +
	"\x16UserLoginQueryResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\"\n" +
	"\x04user\x18\x02 \x01(\v2\x0e.user.UserInfoR\x04user\"\x95\x01\n" +
	"\x0eWxLoginPayload\x12\x1f\n" +
	"\vsession_key\x18\x01 \x01(\tR\n" +
	"sessionKey\x12\x18\n" +
	"\aunionid\x18\x02 \x01(\tR\aunionid\x12\x16\n" +
	"\x06openid\x18\x03 \x01(\tR\x06openid\x12\x18\n" +
	"\aerrcode\x18\x04 \x01(\x05R\aerrcode\x12\x16\n" +
	"\x06errmsg\x18\x05 \x01(\tR\x06errmsg\"z\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x18\n" +
	"\apayload\x18\x04 \x01(\tR\apayload\x12\x10\n" +
	"\x03key\x18\x05 \x01(\tR\x03key\"I\n" +
	"\x13UserInfoModifyQuery\x12\x16\n" +
	"\x06avatar\x18\x01 \x01(\tR\x06avatar\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\"\x1d\n" +
	"\x1bUserInfoModifyQueryResponse\"M\n" +
	"\x11MasterKeySetQuery\x12\x18\n" +
	"\apayload\x18\x01 \x01(\tR\apayload\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x02 \x01(\tR\n" +
	"ciphertext\"-\n" +
	"\x19MasterKeySetQueryResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"6\n" +
	"\x14MasterKeyVerifyQuery\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x01 \x01(\tR\n" +
	"ciphertext\"@\n" +
	"\x1cMasterKeyVerifyQueryResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\"M\n" +
	"\vAppAddQuery\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12*\n" +
	"\apayload\x18\x02 \x01(\v2\x10.user.AppPayloadR\apayload\"\x15\n" +
	"\x13AppAddQueryResponse\"T\n" +
	"\n" +
	"AppPayload\x12&\n" +
	"\x0eaccountPayload\x18\x01 \x01(\tR\x0eaccountPayload\x12\x1e\n" +
	"\n" +
	"pwdPayload\x18\x02 \x01(\tR\n" +
	"pwdPayload\"\x1e\n" +
	"\fAppListQuery\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\";\n" +
	"\x14AppListQueryResponse\x12#\n" +
	"\x05lists\x18\x01 \x03(\v2\r.user.AppInfoR\x05lists\"Y\n" +
	"\aAppInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12*\n" +
	"\apayload\x18\x03 \x01(\v2\x10.user.AppPayloadR\apayloadB\tZ\a./pb;pbb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_user_proto_goTypes = []any{
	(*UserLoginQuery)(nil),               // 0: user.UserLoginQuery
	(*UserLoginQueryResponse)(nil),       // 1: user.UserLoginQueryResponse
	(*WxLoginPayload)(nil),               // 2: user.WxLoginPayload
	(*UserInfo)(nil),                     // 3: user.UserInfo
	(*UserInfoModifyQuery)(nil),          // 4: user.UserInfoModifyQuery
	(*UserInfoModifyQueryResponse)(nil),  // 5: user.UserInfoModifyQueryResponse
	(*MasterKeySetQuery)(nil),            // 6: user.MasterKeySetQuery
	(*MasterKeySetQueryResponse)(nil),    // 7: user.MasterKeySetQueryResponse
	(*MasterKeyVerifyQuery)(nil),         // 8: user.MasterKeyVerifyQuery
	(*MasterKeyVerifyQueryResponse)(nil), // 9: user.MasterKeyVerifyQueryResponse
	(*AppAddQuery)(nil),                  // 10: user.AppAddQuery
	(*AppAddQueryResponse)(nil),          // 11: user.AppAddQueryResponse
	(*AppPayload)(nil),                   // 12: user.AppPayload
	(*AppListQuery)(nil),                 // 13: user.AppListQuery
	(*AppListQueryResponse)(nil),         // 14: user.AppListQueryResponse
	(*AppInfo)(nil),                      // 15: user.AppInfo
}
var file_user_proto_depIdxs = []int32{
	3,  // 0: user.UserLoginQueryResponse.user:type_name -> user.UserInfo
	12, // 1: user.AppAddQuery.payload:type_name -> user.AppPayload
	15, // 2: user.AppListQueryResponse.lists:type_name -> user.AppInfo
	12, // 3: user.AppInfo.payload:type_name -> user.AppPayload
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
